apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-neo4j
  template:
    metadata:
      labels:
        app: kafka-connect-neo4j
    spec:
      containers:
      - name: kafka-connect-neo4j
        image: veedata/kafka-neo4j-connect:latest
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka-service:29092"
        - name: CONNECT_GROUP_ID
          value: "neo4j-connect-cluster"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        ports:
        - containerPort: 8083
