apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app.kubernetes.io/name: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
  type: ClusterIP
